/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monapp;

import static BDD.Configuration.*;
import Model.Colors;
import javax.swing.JOptionPane;

/**
 *
 * @author Ali Abdoulkader Ali
 */
public class Bienvenue extends javax.swing.JFrame {

    ;
    /**
     * Creates new form Bienvenue
     */
    public Bienvenue() {
        initComponents();
        setLocationRelativeTo(null);
        jPanel1.setBackground(Colors.INSTANCE.menuColor());
        copyright.setForeground(Colors.INSTANCE.CopyrightTextColor());
        logout.setBackground(Colors.INSTANCE.primaryColor());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accueil = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        titreMenu = new javax.swing.JLabel();
        boutonLecteur = new javax.swing.JButton();
        boutonOuvrage = new javax.swing.JButton();
        copyright = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        boutonEmprunt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accueil");
        setResizable(false);

        accueil.setBackground(new java.awt.Color(41, 94, 81));
        accueil.setToolTipText("");
        accueil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setBackground(new java.awt.Color(41, 94, 81));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        accueil.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 50, 60));

        jPanel1.setBackground(new java.awt.Color(44, 58, 71));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        titreMenu.setBackground(new java.awt.Color(204, 204, 255));
        titreMenu.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        titreMenu.setForeground(new java.awt.Color(236, 204, 104));
        titreMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-ressources-humaines-48.png"))); // NOI18N
        titreMenu.setText(" Système de Gestion d'une Bibliothèque");
        titreMenu.setToolTipText("");
        titreMenu.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titreMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titreMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        accueil.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 13, -1, -1));

        boutonLecteur.setBackground(new java.awt.Color(72, 219, 251));
        boutonLecteur.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        boutonLecteur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-lecture-64.png"))); // NOI18N
        boutonLecteur.setText("Lecteur");
        boutonLecteur.setToolTipText("Gestion des employés");
        boutonLecteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonLecteurActionPerformed(evt);
            }
        });
        accueil.add(boutonLecteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 189, -1));

        boutonOuvrage.setBackground(new java.awt.Color(0, 204, 51));
        boutonOuvrage.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        boutonOuvrage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-livres-64.png"))); // NOI18N
        boutonOuvrage.setText("Ouvrage");
        boutonOuvrage.setToolTipText("Gestion des promotions");
        boutonOuvrage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonOuvrageActionPerformed(evt);
            }
        });
        accueil.add(boutonOuvrage, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 190, -1));

        copyright.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        copyright.setForeground(new java.awt.Color(255, 204, 102));
        copyright.setText("Copyright © 2021 | Bachir Ibrahim Houmed |All rights reserved");
        accueil.add(copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 563, -1, 36));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/burgundy-library-1.png"))); // NOI18N
        accueil.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 390, 410));

        boutonEmprunt.setBackground(new java.awt.Color(255, 204, 0));
        boutonEmprunt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        boutonEmprunt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-emprunter-un-livre-64.png"))); // NOI18N
        boutonEmprunt.setText("Emprunt");
        boutonEmprunt.setToolTipText("Gestion des congés");
        boutonEmprunt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonEmpruntActionPerformed(evt);
            }
        });
        accueil.add(boutonEmprunt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 189, -1));
        boutonEmprunt.getAccessibleContext().setAccessibleDescription("Gestion des emprunts\n");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accueil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accueil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int input = JOptionPane.showConfirmDialog(this, "Êtes-vous sûr de vous déconnecter ?");
        if (input == 0) {
            this.dispose();
            new Login().setVisible(true);
        }

    }//GEN-LAST:event_logoutActionPerformed

    private void boutonLecteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonLecteurActionPerformed

        this.dispose();
        new Lecteur().setVisible(true);

    }//GEN-LAST:event_boutonLecteurActionPerformed

    private void boutonOuvrageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonOuvrageActionPerformed
        this.dispose();
        new Ouvrage().setVisible(true);
    }//GEN-LAST:event_boutonOuvrageActionPerformed

    private void boutonEmpruntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonEmpruntActionPerformed
                this.dispose();
        new Emprunt().setVisible(true);
    }//GEN-LAST:event_boutonEmpruntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accueil;
    private javax.swing.JButton boutonEmprunt;
    private javax.swing.JButton boutonLecteur;
    private javax.swing.JButton boutonOuvrage;
    private javax.swing.JLabel copyright;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JLabel titreMenu;
    // End of variables declaration//GEN-END:variables
}
