/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monapp;

import Model.*;
import static BDD.Configuration.*;
import static Model.Country.*;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ali Abdoulkader Ali
 */

public class Emprunt extends javax.swing.JFrame {

    ResultSet res, rd,rd1,res1,res2;
    String SQL, idt_emprt="num_lecteur",table = "emprunt",colonnes ="num_ouv,num_lecteur,date_pret,date_remise";
    String nomauteur,date_pret_emp, date_remise_emp,test,numouvrage, num_lect;
    int nbre, r=0;
    //Country[] listCountry = createCountryList();
    //private static final String PATTERN = "^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";
    
    /**
     * Creates new form Lecteur
     */
    public Emprunt() {
        initComponents();
        supprimer.setEnabled(false);
        top.setBackground(Colors.INSTANCE.secondaryColor());
        setLocationRelativeTo(null);
        setBackground(Colors.INSTANCE.secondaryColor());
        body.setBackground(Colors.INSTANCE.secondaryColor());
        bottom.setBackground(Colors.INSTANCE.secondaryColor());
        top.setBackground(Colors.INSTANCE.primaryColor());
        //numouv.setFont(new java.awt.Font("Tahoma", 1, 13));

        table();

    }
    
    public void CompteurOuvragesEmpruntes(){
        res = Compteur(table);
        try {
            res.next();
            stat_ouvrages.setText(res.getInt("Count(*)")+"");
        } catch (SQLException ex) {
            Logger.getLogger(Emprunt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void table() {
        String colonnes = "titre_ouv, nom_lecteur, date_pret, date_remise";
        String[] colonnesOuvrage = {"titre_ouv","num_ouv","nom_auteur","exemplaire"};
        String colonnesLecteur = "prenom_lecteur,nom_lecteur,num_lecteur,type_lecteur";
        
        res1 = select(colonnesOuvrage, "ouvrage");
        res = selectInnerJoin1(table,"ouvrage","lecteur",colonnes,"num_ouv","num_lecteur");
        res2 = selectInnerJoin("lecteur","categorie",colonnesLecteur,"code_categorie");
        
        maTable.setModel(DbUtils.resultSetToTableModel(res1));
        maTable1.setModel(DbUtils.resultSetToTableModel(res2));
        maTable2.setModel(DbUtils.resultSetToTableModel(res));
        ajouter.setEnabled(true);
        CompteurOuvragesEmpruntes();
        
    }

    public void actualiser() {
        numLect.setText("");
        numOuvrage.setText("");
        datepret.setCalendar(null);
        dateremise.setCalendar(null);
        supprimer.setEnabled(false);
        ajouter.setEnabled(true);
        maTable.clearSelection(); 
        maTable.clearSelection();
        maTable2.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        bottom = new javax.swing.JPanel();
        infoperso = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        numLect = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        numOuvrage = new javax.swing.JTextField();
        datepret = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        dateremise = new com.toedter.calendar.JDateChooser();
        operations = new javax.swing.JPanel();
        ajouter = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        maTable = new javax.swing.JTable();
        vider = new javax.swing.JButton();
        copyright = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        stat_ouvrages = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        maTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        maTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(236, 204, 104));
        jLabel1.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 204, 104));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-emprunter-un-livre-64.png"))); // NOI18N
        jLabel1.setText(" Gestion des Emprunts");
        jLabel1.setToolTipText("");

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-48.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addGap(450, 450, 450)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(topLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(back)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        bottom.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Détails sur l'ouvrage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(236, 204, 104))); // NOI18N

        infoperso.setBackground(Colors.INSTANCE.secondaryColor());
        infoperso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(236, 204, 104))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(Colors.INSTANCE.textColor());
        jLabel2.setText("Numéro Lecteur :");

        numLect.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        numLect.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(Colors.INSTANCE.textColor());
        jLabel5.setText("Date de prêt :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setForeground(Colors.INSTANCE.textColor()
        );
        jLabel16.setText("Numéro Ouvrage :");

        numOuvrage.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        numOuvrage.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(Colors.INSTANCE.textColor());
        jLabel7.setText("Date de rémise :");

        javax.swing.GroupLayout infopersoLayout = new javax.swing.GroupLayout(infoperso);
        infoperso.setLayout(infopersoLayout);
        infopersoLayout.setHorizontalGroup(
            infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infopersoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infopersoLayout.createSequentialGroup()
                        .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numOuvrage, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(numLect))
                        .addContainerGap())
                    .addGroup(infopersoLayout.createSequentialGroup()
                        .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datepret, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateremise, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))))
        );
        infopersoLayout.setVerticalGroup(
            infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infopersoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numLect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(numOuvrage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(datepret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(dateremise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        operations.setBackground(Colors.INSTANCE.primaryColor());
        operations.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opérations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(236, 204, 104))); // NOI18N

        ajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-20.png"))); // NOI18N
        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-save-close-20.png"))); // NOI18N
        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-delete-20.png"))); // NOI18N
        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        annuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cancel-20.png"))); // NOI18N
        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout operationsLayout = new javax.swing.GroupLayout(operations);
        operations.setLayout(operationsLayout);
        operationsLayout.setHorizontalGroup(
            operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationsLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(ajouter)
                .addGap(34, 34, 34)
                .addComponent(modifier)
                .addGap(34, 34, 34)
                .addComponent(supprimer)
                .addGap(32, 32, 32)
                .addComponent(annuler)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        operationsLayout.setVerticalGroup(
            operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, operationsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouter)
                    .addComponent(modifier)
                    .addComponent(supprimer)
                    .addComponent(annuler))
                .addContainerGap())
        );

        maTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titre de l'Ouvrage", "Numéro Ouvrage", "Nom de l'Auteur", "Exemplaire"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        maTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(maTable);

        vider.setText("Vider la table");
        vider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viderActionPerformed(evt);
            }
        });

        copyright.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        copyright.setForeground(new java.awt.Color(255, 204, 102));
        copyright.setText("Copyright © 2021 | Bachir |All rights reserved");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(Colors.INSTANCE.textColor());
        jLabel6.setText("Nombre des ouvrages empruntés :");

        stat_ouvrages.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        stat_ouvrages.setForeground(new java.awt.Color(204, 204, 255));
        stat_ouvrages.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        maTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prenom du Lecteur", "Nom du Lecteur", "Numéro Lecteur", "Catégorie Lecteur"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        maTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(maTable1);

        maTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titre de l'Ouvrage", "Nom du Lecteur", "Date de Prêt", "Date de Remise"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        maTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(maTable2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("LIVRES EMPRUNTES");

        javax.swing.GroupLayout bottomLayout = new javax.swing.GroupLayout(bottom);
        bottom.setLayout(bottomLayout);
        bottomLayout.setHorizontalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addComponent(copyright)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(bottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoperso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bottomLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(operations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bottomLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(27, 27, 27)
                                .addComponent(stat_ouvrages, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(bottomLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(vider, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bottomLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(174, 174, 174))
        );
        bottomLayout.setVerticalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoperso, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bottomLayout.createSequentialGroup()
                        .addComponent(operations, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(vider)
                        .addGap(95, 95, 95)
                        .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(stat_ouvrages, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyright, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addComponent(top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        this.dispose();
        new Bienvenue().setVisible(true);

    }//GEN-LAST:event_backMouseClicked

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed

        recuperation();
        String[] colonnes = {"num_ouv", "num_lecteur", "date_pret", "date_remise"};
        //String[] colonnes = {"num_emprunt","num_cni","num_ouv","nom_lecteur","date_pret","date_remise"};
         Object[] values = {Integer.valueOf(numouvrage),Integer.valueOf(num_lect),date_pret_emp,date_remise_emp};
       // res = selectInnerJoin1(table,"ouvrage","lecteur",colonnes,"num_ouv","num_lecteur");
        res = selectCondition(table,idt_emprt,num_lect);
        if (!numouvrage.equals("") && !num_lect.equals("") && !date_pret_emp.equals("") && !date_remise_emp.equals("")
                ) {
           rd = selectCondition1("ouvrage","num_ouv ='"+numouvrage+"'");
           rd1 = selectCondition1("lecteur", "num_lecteur='"+num_lect+"'");
           
           
         try{
                while(rd.next() && rd1.next()){
                   test=rd.getString("num_ouv");
                   nbre = Integer.valueOf(rd.getString("exemplaire"));
                   
                   if(test != null){
                       if (nbre==0){
                JOptionPane.showMessageDialog(this, "Il n y a pas d'exemplaire de ce livre. Emprunt impossible!!!"); 
                     //r++;
                       }else{
                  executionUpdate("UPDATE ouvrage SET exemplaire=exemplaire-1 "
                               + " WHERE num_ouv= '"+numouvrage+"'" );
                             
                if (dateremise.getDate().after(datepret.getDate())) {
                    insert(table, colonnes, values);
                }else{
                JOptionPane.showMessageDialog(this, "La date de remise doit ête supérieur à la date de prêt !!");
            }
                System.out.println("Emprunt effectué");
                    r++;
                       }
                   }
                }
         } catch (SQLException ex) {
                Logger.getLogger(Emprunt.class.getName()).log(Level.SEVERE, null, ex);
         }
              /* if (dateremise.getDate().after(datepret.getDate())) {
                    insert(table, colonnes, values);
                }else{
                JOptionPane.showMessageDialog(this, "La date de remise doit ête supérieur à la date de prêt !!");
            }*/
         } else {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs !");
        }
        actualiser();
        table();
    }//GEN-LAST:event_ajouterActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        DefaultTableModel model = (DefaultTableModel) maTable2.getModel();

         recuperation();

         String[] colonnes = {"num_ouv","num_lecteur","date_pret","date_remise"};
         String[] valeurs = {numouvrage,num_lect,date_pret_emp,date_remise_emp};

        String cni = String.valueOf(model.getValueAt(maTable.getSelectedRow(), 0));

        updateTable(table, colonnes, valeurs,idt_emprt,cni);

        actualiser();
        table();

    }//GEN-LAST:event_modifierActionPerformed

    private void maTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) maTable.getModel();
            int selectedRowIndex = maTable.getSelectedRow();
            numOuvrage.setText(model.getValueAt(selectedRowIndex, 1).toString());
    }//GEN-LAST:event_maTableMouseClicked

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        actualiser();
    }//GEN-LAST:event_annulerActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        DefaultTableModel model = (DefaultTableModel) maTable.getModel();
        int ligne = maTable2.getSelectedRow();
        String valeur = String.valueOf(model.getValueAt(ligne, 1));
        if (maTable2.getSelectedRowCount() == 1) {
            supprimer.setEnabled(true);
            deleteColumn(table, idt_emprt, valeur);

            if (maTable2.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table vide !");
            }
        } else {
            supprimer.setEnabled(true);
        }

        actualiser();
        table();
    }//GEN-LAST:event_supprimerActionPerformed

    private void viderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viderActionPerformed
        dbConn();
        SQL = "TRUNCATE TABLE " + table;
        executionUpdate(SQL);
        table();
    }//GEN-LAST:event_viderActionPerformed


    private void maTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maTable1MouseClicked
            DefaultTableModel model = (DefaultTableModel) maTable1.getModel();
            int selectedRowIndex = maTable1.getSelectedRow();
            numLect.setText(model.getValueAt(selectedRowIndex, 2).toString());
    }//GEN-LAST:event_maTable1MouseClicked

    private void maTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maTable2MouseClicked
            DefaultTableModel model = (DefaultTableModel) maTable2.getModel();

        int selectedRowIndex = maTable2.getSelectedRow();
        Date date = null, date1 = null;
        try {
            date = new SimpleDateFormat("dd-MM-yyyy").parse((String) model.getValueAt(selectedRowIndex, 2));
            date1 = new SimpleDateFormat("dd-MM-yyyy").parse((String) model.getValueAt(selectedRowIndex, 3));
            numLect.setText(model.getValueAt(selectedRowIndex, 1).toString());
            numOuvrage.setText(model.getValueAt(selectedRowIndex, 0).toString());
            datepret.setDate(date);
            dateremise.setDate(date1);
            ajouter.setEnabled(false);
            supprimer.setEnabled(true);
        } catch (ParseException ex) {
            Logger.getLogger(Emprunt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_maTable2MouseClicked

    public void recuperation() {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            String daterecup = sdf.format(datepret.getDate());
            String daterecup1 = sdf.format(dateremise.getDate());

            numouvrage = numOuvrage.getText();
            num_lect = numLect.getText();
            date_pret_emp= daterecup;
            date_remise_emp= daterecup1;
            
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Saisir la date de prêt et la date de remise");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Emprunt().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JButton annuler;
    private javax.swing.JLabel back;
    private javax.swing.JPanel body;
    private javax.swing.JPanel bottom;
    private javax.swing.JLabel copyright;
    private com.toedter.calendar.JDateChooser datepret;
    private com.toedter.calendar.JDateChooser dateremise;
    private javax.swing.JPanel infoperso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable maTable;
    private javax.swing.JTable maTable1;
    private javax.swing.JTable maTable2;
    private javax.swing.JButton modifier;
    private javax.swing.JTextField numLect;
    private javax.swing.JTextField numOuvrage;
    private javax.swing.JPanel operations;
    private javax.swing.JLabel stat_ouvrages;
    private javax.swing.JButton supprimer;
    private javax.swing.JPanel top;
    private javax.swing.JButton vider;
    // End of variables declaration//GEN-END:variables
}
