/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monapp;

import Model.*;
import static BDD.Configuration.*;
import static Model.Country.*;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ali Abdoulkader Ali
 */

public class Lecteur extends javax.swing.JFrame {

    ResultSet res, rd;
    String SQL, table = "lecteur",colonnes ="num_lecteur,code_categorie,nom_lecteur,prenom_lecteur,date_nais,lieu_nais";
    String num_cni,noml, prenoml, typel, dateNaissancel, lieunaissancel;
    //Country[] listCountry = createCountryList();
    //private static final String PATTERN = "^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";

    /**
     * Creates new form Lecteur
     */ 
    public Lecteur() {
        initComponents();
        supprimer.setEnabled(false);
        top.setBackground(Colors.INSTANCE.secondaryColor());
        setLocationRelativeTo(null);
        setBackground(Colors.INSTANCE.secondaryColor());
        body.setBackground(Colors.INSTANCE.secondaryColor());
        bottom.setBackground(Colors.INSTANCE.secondaryColor());
        top.setBackground(Colors.INSTANCE.primaryColor());
      // cni.setFont(new java.awt.Font("Tahoma", 1, 13));

        table();

    }
    
    public void CompteurAbonnes(){
        res = Compteur(table);
        try {
            res.next();
            abonnes.setText(res.getInt("Count(*)")+"");
        } catch (SQLException ex) {
            Logger.getLogger(Lecteur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void table() {
        
        String[] colonnes = {"prenom_lecteur","nom_lecteur","num_lecteur","code_categorie","date_nais","lieu_nais"};
        res = select(colonnes, "lecteur");
        
        maTable.setModel(DbUtils.resultSetToTableModel(res));
        ajouter.setEnabled(true);
        CompteurAbonnes();

    }

    public void actualiser() {
        prenom.setText("");
        nom.setText("");
        type.setSelectedIndex(0);
        dateNaissance.setCalendar(null);
        lieunaissance.setText("");
        supprimer.setEnabled(false);
        ajouter.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        bottom = new javax.swing.JPanel();
        infoperso = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dateNaissance = new com.toedter.calendar.JDateChooser();
        lieunaissance = new javax.swing.JTextField();
        operations = new javax.swing.JPanel();
        ajouter = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        maTable = new javax.swing.JTable();
        vider = new javax.swing.JButton();
        recherche = new javax.swing.JPanel();
        rech_nom = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        abonnes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(236, 204, 104));
        jLabel1.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 204, 104));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-lecture-64.png"))); // NOI18N
        jLabel1.setText(" Gestion des Lecteurs");
        jLabel1.setToolTipText("");

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-48.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(331, 331, 331))
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(topLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(back)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        bottom.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Détails sur le lecteur", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(236, 204, 104))); // NOI18N

        infoperso.setBackground(Colors.INSTANCE.secondaryColor());
        infoperso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(236, 204, 104))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(Colors.INSTANCE.textColor());
        jLabel2.setText("Prénom :");

        prenom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(Colors.INSTANCE.textColor());
        jLabel4.setText("Catégorie");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(Colors.INSTANCE.textColor());
        jLabel5.setText("Lieu de Naissance");

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir ...", "Employé", "Professeur", "Etudiant" }));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setForeground(Colors.INSTANCE.textColor()
        );
        jLabel16.setText("Nom :");

        nom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setForeground(Colors.INSTANCE.textColor());
        jLabel9.setText("Date De Naissance :");

        javax.swing.GroupLayout infopersoLayout = new javax.swing.GroupLayout(infoperso);
        infoperso.setLayout(infopersoLayout);
        infopersoLayout.setHorizontalGroup(
            infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infopersoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infopersoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateNaissance, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                    .addGroup(infopersoLayout.createSequentialGroup()
                        .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel16))
                        .addGap(27, 27, 27)
                        .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(type, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lieunaissance)
                            .addComponent(nom)
                            .addComponent(prenom))
                        .addContainerGap())))
        );
        infopersoLayout.setVerticalGroup(
            infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infopersoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lieunaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        operations.setBackground(Colors.INSTANCE.primaryColor());
        operations.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opérations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(236, 204, 104))); // NOI18N

        ajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-20.png"))); // NOI18N
        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-save-close-20.png"))); // NOI18N
        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-delete-20.png"))); // NOI18N
        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        annuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cancel-20.png"))); // NOI18N
        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout operationsLayout = new javax.swing.GroupLayout(operations);
        operations.setLayout(operationsLayout);
        operationsLayout.setHorizontalGroup(
            operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationsLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(ajouter)
                .addGap(34, 34, 34)
                .addComponent(modifier)
                .addGap(34, 34, 34)
                .addComponent(supprimer)
                .addGap(32, 32, 32)
                .addComponent(annuler)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        operationsLayout.setVerticalGroup(
            operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, operationsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouter)
                    .addComponent(modifier)
                    .addComponent(supprimer)
                    .addComponent(annuler))
                .addContainerGap())
        );

        maTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prenom", "Nom", "Numéro lecteur", "Catégorie", "Date de naissance", "Lieu de naissance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        maTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(maTable);

        vider.setText("Vider la table");
        vider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viderActionPerformed(evt);
            }
        });

        recherche.setBackground(Colors.INSTANCE.primaryColor());
        recherche.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recherche", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(236, 204, 104))); // NOI18N

        rech_nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rech_nomKeyReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setForeground(Colors.INSTANCE.textColor());
        jLabel17.setText("Nom :");

        javax.swing.GroupLayout rechercheLayout = new javax.swing.GroupLayout(recherche);
        recherche.setLayout(rechercheLayout);
        rechercheLayout.setHorizontalGroup(
            rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rechercheLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rech_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rechercheLayout.setVerticalGroup(
            rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rechercheLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rech_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        copyright.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        copyright.setForeground(new java.awt.Color(255, 204, 102));
        copyright.setText("Copyright © 2021 | Bachir |All rights reserved");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(Colors.INSTANCE.textColor());
        jLabel6.setText("Nombre des lecteurs abonnés :");

        abonnes.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        abonnes.setForeground(new java.awt.Color(204, 204, 255));
        abonnes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout bottomLayout = new javax.swing.GroupLayout(bottom);
        bottom.setLayout(bottomLayout);
        bottomLayout.setHorizontalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
                    .addGroup(bottomLayout.createSequentialGroup()
                        .addComponent(infoperso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(operations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bottomLayout.createSequentialGroup()
                                .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vider, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71))
                            .addGroup(bottomLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(abonnes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(bottomLayout.createSequentialGroup()
                .addComponent(copyright)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bottomLayout.setVerticalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoperso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bottomLayout.createSequentialGroup()
                        .addComponent(operations, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bottomLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bottomLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(vider)))
                        .addGap(67, 67, 67)
                        .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(abonnes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 75, 75)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(copyright, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addComponent(top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        this.dispose();
        new Bienvenue().setVisible(true);

    }//GEN-LAST:event_backMouseClicked
    
    
    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed

        recuperation();

        String[] colonnes = {"code_categorie","nom_lecteur","prenom_lecteur","date_nais","lieu_nais"};
        Object[] values = {Integer.valueOf(categorie()),noml,prenoml,dateNaissancel,lieunaissancel};
        
        //res = selectCondition(table, "num_lecteur",num_cni);
        if (!noml.isEmpty() && !prenoml.equals("") && !dateNaissancel.equals("") 
                && type.getSelectedIndex() != 0 && !lieunaissance.equals("")
                ) {

           /* if (dateInscription.getDate().after(dateNaissance.getDate())) {*/
                insert("lecteur", colonnes, values);
                System.out.println("lecteur ajouté");
           /* }else{
                JOptionPane.showMessageDialog(this, "La date d'inscription doit ête supérieur à la date de naissance !!");
            }*/

        } else {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs !");
        }
        actualiser();
        table();
    }//GEN-LAST:event_ajouterActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        DefaultTableModel model = (DefaultTableModel) maTable.getModel();

        recuperation();

        String[] colonnes = {"code_categorie","nom_lecteur","prenom_lecteur","date_nais","lieu_nais"};
        Object[] valeurs = {Integer.valueOf(categorie()),noml,prenoml,dateNaissancel,lieunaissancel};
        
        String idnum = String.valueOf(model.getValueAt(maTable.getSelectedRow(), 2));

        updateTable(table, colonnes, valeurs,"num_lecteur", idnum);

        actualiser();
        table();

    }//GEN-LAST:event_modifierActionPerformed

    private void maTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) maTable.getModel();

        int selectedRowIndex = maTable.getSelectedRow();
        Date date = null, date1 = null;
        try {
            date = new SimpleDateFormat("dd-MM-yyyy").parse((String) model.getValueAt(selectedRowIndex, 4));
            //date1 = new SimpleDateFormat("dd-MM-yyyy").parse((String) model.getValueAt(selectedRowIndex, 5));
            //cni.setText(model.getValueAt(selectedRowIndex, 0).toString());
            prenom.setText(model.getValueAt(selectedRowIndex, 0).toString());
            nom.setText(model.getValueAt(selectedRowIndex, 1).toString());
            type.setSelectedItem(model.getValueAt(selectedRowIndex, 3).toString());
            dateNaissance.setDate(date);
            lieunaissance.setText(model.getValueAt(selectedRowIndex, 5).toString());
            ajouter.setEnabled(false);
            supprimer.setEnabled(true);
        } catch (ParseException ex) {
            Logger.getLogger(Lecteur.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_maTableMouseClicked

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        actualiser();
    }//GEN-LAST:event_annulerActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        DefaultTableModel model = (DefaultTableModel) maTable.getModel();
        int ligne = maTable.getSelectedRow();
        String idnum = String.valueOf(model.getValueAt(ligne, 2));
        if (maTable.getSelectedRowCount() == 1) {
            supprimer.setEnabled(true);
            deleteColumn(table, "num_lecteur",idnum);

            if (maTable.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table vide !");
            }
        } else {
            supprimer.setEnabled(true);
        }
        
        actualiser();
        table();
    }//GEN-LAST:event_supprimerActionPerformed

    private void viderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viderActionPerformed
        dbConn();
        SQL = "TRUNCATE TABLE " + table;
        executionUpdate(SQL);
        table();
    }//GEN-LAST:event_viderActionPerformed


    private void rech_nomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rech_nomKeyReleased
        String nom = rech_nom.getText();
        maTable.setModel(DbUtils.resultSetToTableModel(searchByName(table,colonnes,nom)));
    }//GEN-LAST:event_rech_nomKeyReleased

    public void recuperation() {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            String daterecup = sdf.format(dateNaissance.getDate());
            //String daterecup1 = sdf.format(dateInscription.getDate());
            String resultat="";
            if(type.getSelectedItem().toString()== "Employé"){
                
            }
            noml = nom.getText().toUpperCase().trim();
            prenoml = prenom.getText();
            typel = categorie();
            dateNaissancel = daterecup;
            lieunaissancel= lieunaissance.getText();
            
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Saisir la date de naissance");
        }

    }
    
        public String categorie(){
            String resultat="";
        if(type.getSelectedItem().toString() == "Employé")
            resultat= "1";
        else if (type.getSelectedItem().toString() == "Professeur")
            resultat = "2";
        else
            resultat = "3";
        return resultat;
        }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lecteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lecteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lecteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lecteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Lecteur().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abonnes;
    private javax.swing.JButton ajouter;
    private javax.swing.JButton annuler;
    private javax.swing.JLabel back;
    private javax.swing.JPanel body;
    private javax.swing.JPanel bottom;
    private javax.swing.JLabel copyright;
    private com.toedter.calendar.JDateChooser dateNaissance;
    private javax.swing.JPanel infoperso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lieunaissance;
    private javax.swing.JTable maTable;
    private javax.swing.JButton modifier;
    private javax.swing.JTextField nom;
    private javax.swing.JPanel operations;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField rech_nom;
    private javax.swing.JPanel recherche;
    private javax.swing.JButton supprimer;
    private javax.swing.JPanel top;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JButton vider;
    // End of variables declaration//GEN-END:variables
}
